image: docker:stable

services:
  - docker:dind

stages:
  - docker-test
  - docker-build
  - build
  - test

variables:
  DOCKER_IMAGE_TAG: "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA"

docker-test:
  stage: docker-test
  script:
    - docker build -t $DOCKER_IMAGE_TAG .
    - docker run $DOCKER_IMAGE_TAG go test ./calc

docker-build:
  stage: docker-build
  script:
    - docker build -t $DOCKER_IMAGE_TAG .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $DOCKER_IMAGE_TAG
  only:
    - master
    - main

before_script:
  - go mod tidy
  - go mod download

build:
  stage: build
  image: golang:1.20-alpine
  script:
    - go build -o /main
  artifacts:
    paths:
      - main

test:
  stage: test
  image: golang:1.20-alpine
  script:
    - go test ./calc





#include:
#  - local: "/gitlab-ci/.gitlab-ci_docker.yml"
#  - local: "/gitlab-ci/.gitlab-ci_go.yml"
#
#stages:
#  - docker-test
#  - docker-build
#  - build
#  - test
